### ISSUE TITLE
No member named 'get'

### ISSUE THREAD

**Issue by 772** [Fulgen301/LCEdit#7]
[ 73%] Building CXX object CMakeFiles/plugin_graphicsviewer.dir/src/plugins/graphicsviewer.cpp.o
/home/j/LCEdit/src/plugins/graphicsviewer.cpp: In member function ‘virtual ExecPolicy GraphicsViewerPlugin::treeItemChanged(LCTreeWidgetItem*, LCTreeWidgetItem*)’:
/home/j/LCEdit/src/plugins/graphicsviewer.cpp:55:30: error: ‘QIODevicePtr {aka class QSharedPointer<QIODevice>}’ has no member named ‘get’
   QImageReader reader(device.get());

[ 94%] Building CXX object CMakeFiles/plugin_search.dir/src/plugins/search.cpp.o
/home/j/LCEdit/src/plugins/search.cpp: In member function ‘bool FileSearchPlugin::waitForDevice(const QIODevicePtr&)’:
/home/j/LCEdit/src/plugins/search.cpp:88:18: error: ‘const QIODevicePtr {aka const class QSharedPointer<QIODevice>}’ has no member named ‘get’
   connect(device.get(), &QIODevice::aboutToClose, this, &FileSearchPlugin::deviceAboutToClose);
                  ^~~
/home/j/LCEdit/src/plugins/search.cpp:90:21: error: ‘const QIODevicePtr {aka const class QSharedPointer<QIODevice>}’ has no member named ‘get’
   disconnect(device.get(), &QIODevice::aboutToClose, this, &FileSearchPlugin::deviceAboutToClose);

The function 'get' creates 4 errors while making this project, there is another 'get' in c4group.cpp. I was only able to build LCEdit after I commented these blocks out.

**Comment by Fulgen301** [comment]
This error means that your Qt version is lower than Qt 5.11, which is required by LCEdit. If your distribution's package manager doesn't provide this version, you might wanna use the autobuild instead.
However, in this particular case, changing `get()` to `data()` should not be a problem.

**Comment by 772** [comment]
Indeed, Qt 5.9.5 is the newest on mine.
