### ISSUE TITLE
Feature request: Update directory function

### ISSUE THREAD

**Issue by Somebodyisnobody** [Fulgen301/LCEdit#9]
LCedit should have the option to reload the current working directory maybe via F5 and/or a menu point under "File" or "Actions"

**Comment by Fulgen301** [comment]
This is somehow implemented since 40b541768ef67220df829186c69229f6916e054f, which is in v1.0, and got F5 and an action added in 74b71e823e831a0df014399fd03a111a21041f91. Unfortunately, the autobuilds are currently broken =/
